// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqou2JU0NchwdpIHPqR1Dh5swMhhmy0Ds',
    appId: '1:235091177023:web:1554224a08081206a6d28a',
    messagingSenderId: '235091177023',
    projectId: 'fir-chat-app-v2',
    authDomain: 'fir-chat-app-v2.firebaseapp.com',
    storageBucket: 'fir-chat-app-v2.appspot.com',
    measurementId: 'G-QH2MTHG7Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGNxfcdGHul0eqFKJC2_fRCoWpZT_-_I',
    appId: '1:235091177023:android:49e941b8cb3ffc92a6d28a',
    messagingSenderId: '235091177023',
    projectId: 'fir-chat-app-v2',
    storageBucket: 'fir-chat-app-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgUYfXnA5T8IUmuuXQ-rnQIgfcnHH1GYA',
    appId: '1:235091177023:ios:67c868abab0ae88da6d28a',
    messagingSenderId: '235091177023',
    projectId: 'fir-chat-app-v2',
    storageBucket: 'fir-chat-app-v2.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgUYfXnA5T8IUmuuXQ-rnQIgfcnHH1GYA',
    appId: '1:235091177023:ios:67c868abab0ae88da6d28a',
    messagingSenderId: '235091177023',
    projectId: 'fir-chat-app-v2',
    storageBucket: 'fir-chat-app-v2.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqou2JU0NchwdpIHPqR1Dh5swMhhmy0Ds',
    appId: '1:235091177023:web:521498fd74f4458ea6d28a',
    messagingSenderId: '235091177023',
    projectId: 'fir-chat-app-v2',
    authDomain: 'fir-chat-app-v2.firebaseapp.com',
    storageBucket: 'fir-chat-app-v2.appspot.com',
    measurementId: 'G-7TQGMZSDL7',
  );
}
